-- NOT EXECUTED by Codex.
-- Manual maintenance-window verification for the Auth P0 migration sequence:
--   20260724000000_account_provisioning_history_containment.sql
--   20260724000900_auth_p0_owner_seat_preflight.sql
--   20260724001000_auth_p0_provisioning_authorization_lockdown.sql
--   20260724001100_auth_p0_client_active_binding_lockdown.sql
--   20260724001200_auth_p0_authority_mutation_guards.sql
--   20260724001300_auth_magic_link_send_reservation.sql
--   20260724001400_auth_p0_sandbox_execute_revocation.sql
--   20260724001500_auth_p0_final_connector_acl_seal.sql
--   20260724001600_auth_p0_runtime_sql_expression_repair.sql
--
-- Run only through the approved Lovable/Supabase maintenance connection after
-- the first seven migrations (00000 through 01400) report applied and before
-- the final 01500/01600 repair-and-seal sequence. This file is read-only and
-- wrapped in a transaction that always rolls back.
--
-- Operator checklist (record results beside the release SHA):
-- [ ] Before applying any pending migration, run the read-only 20260724000900
--     Owner-seat verification preflight through Lovable. Capture whether
--     20260722233000/20260722233042 already ran, the exact candidate rows, and
--     require zero unresolved candidates before migration application.
-- [ ] Keep the public sign-in/callback and team/client authority mutation paths
--     in maintenance mode for the entire migration batch. Migration 00000 is
--     superseded by 01000; no request may execute its older resolver between
--     those two commits.
-- [ ] Confirm versions 20260724000900..01300 are ordered after 20260724000000.
-- [ ] Run this entire file; require zero exceptions and a final ROLLBACK.
-- [ ] Canary zero-history account: callback resolves NULL company, creates no
--     organization/Owner seat, and displays the explicit unprovisioned state.
-- [ ] Canary exact invite: two pending rows for one email; accepting one changes
--     only that invite and is idempotent for the same authenticated user.
-- [ ] Canary exact client access: pending is unreadable; accepting the exact row
--     binds it; another row for the email remains pending and unreadable.
-- [ ] Before applying 011, active client rows are either exact-user bound or
--     the migration aborts; bound rows with NULL accepted_by repair to that
--     same user, while unbound/conflicting rows are never assigned by email.
-- [ ] Canary mid-session revocation: disable the company seat and revoke client
--     access from a second admin session; the already-open session loses its
--     next server-authorized read/write without a new sign-in.
-- [ ] Canary direct membership DML: authenticated INSERT/UPDATE/DELETE fails;
--     the bounded update_organization_membership_authority RPC still works.
-- [ ] Canary secure invite reissue: a different active manage-team caller can
--     rebind invited_by only to themself on the same exact pending row.
-- [ ] Two concurrent reserve_auth_magic_link_send calls with one dedupe key:
--     exactly one returns reserved=true; the other returns reserved=false with
--     the same pending row. No second Auth token is generated by the app test.
-- [ ] Exact Auth lookup returns zero/one user and browser roles receive 42501.

BEGIN;

SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';

DO $auth_p0_verify$
DECLARE
  v_ensure text;
  v_invite text;
  v_client_finalize text;
  v_client_read text;
  v_project_read text;
  v_project_manage text;
  v_project_assignment text;
  v_member_update text;
  v_invite_guard text;
  v_reservation text;
  v_auth_lookup text;
BEGIN
  v_ensure := pg_catalog.pg_get_functiondef(
    'public.ensure_user_account(uuid,text,text)'::regprocedure
  );
  v_invite := pg_catalog.pg_get_functiondef(
    'public.finalize_invite_acceptance(uuid)'::regprocedure
  );
  v_client_finalize := pg_catalog.pg_get_functiondef(
    'public.finalize_client_access_acceptance(uuid)'::regprocedure
  );
  v_client_read := pg_catalog.pg_get_functiondef(
    'public.can_read_client_project(uuid)'::regprocedure
  );
  v_project_read := pg_catalog.pg_get_functiondef(
    'public.can_read_project(uuid)'::regprocedure
  );
  v_project_manage := pg_catalog.pg_get_functiondef(
    'public.can_manage_project(uuid)'::regprocedure
  );
  v_project_assignment := pg_catalog.pg_get_functiondef(
    'public.tg_projects_creator_assignment()'::regprocedure
  );
  v_member_update := pg_catalog.pg_get_functiondef(
    'public.update_organization_membership_authority(uuid,public.account_role,public.member_status,jsonb)'::regprocedure
  );
  v_invite_guard := pg_catalog.pg_get_functiondef(
    'public.tg_guard_organization_invite_authority()'::regprocedure
  );
  v_reservation := pg_catalog.pg_get_functiondef(
    'public.reserve_auth_magic_link_send(text,text,text,text,jsonb)'::regprocedure
  );
  v_auth_lookup := pg_catalog.pg_get_functiondef(
    'public.lookup_auth_user_by_email_exact(text)'::regprocedure
  );

  -- zero-history account resolution: profile + existing active seat only.
  IF position(
    'insert into public.organizations' IN pg_catalog.lower(v_ensure)
  ) > 0
    OR position(
      'insert into public.organization_memberships' IN pg_catalog.lower(v_ensure)
    ) > 0
    OR position(
      'organization_invites' IN pg_catalog.lower(v_ensure)
    ) > 0
    OR position(
      'overwatch_access_email_key' IN pg_catalog.lower(v_ensure)
    ) > 0
    OR position(
      'm.status = ''active''' IN pg_catalog.lower(v_ensure)
    ) = 0 THEN
    RAISE EXCEPTION 'zero-history provisioning is not fail-closed';
  END IF;

  -- Exact invite/client finalizers; no same-email sweep or pending authority.
  IF position(
    'i.id = p_invite_id' IN pg_catalog.lower(v_invite)
  ) = 0
    OR position(
      'for update of i' IN pg_catalog.lower(v_invite)
    ) = 0
    OR position(
      'overwatch_access_email_key' IN pg_catalog.lower(v_invite)
    ) > 0
    OR position(
      'inviter.status = ''active''' IN pg_catalog.lower(v_invite)
    ) = 0
    OR position(
      'company.manage_team' IN pg_catalog.lower(v_invite)
    ) = 0
    OR position(
      'access_row.id = p_client_access_id' IN pg_catalog.lower(v_client_finalize)
    ) = 0
    OR position(
      'access_row.status = ''active''' IN pg_catalog.lower(v_client_read)
    ) = 0
    OR position(
      'access_row.client_user_id = auth.uid()' IN pg_catalog.lower(v_client_read)
    ) = 0
    OR position(
      'access_row.accepted_by = auth.uid()' IN pg_catalog.lower(v_client_read)
    ) = 0
    OR position(
      'auth.jwt()' IN pg_catalog.lower(v_client_read)
    ) > 0 THEN
    RAISE EXCEPTION 'exact invite/client acceptance containment failed';
  END IF;

  -- owner_id is attribution, never live authorization. Project creation may
  -- add only a scoped project manager assignment.
  IF position(
    'owner_id = auth.uid()' IN pg_catalog.lower(v_project_read)
  ) > 0
    OR position(
      'owner_id = auth.uid()' IN pg_catalog.lower(v_project_manage)
    ) > 0
    OR position(
      'values (new.id, new.owner_id, ''manager'', ''active'')'
      IN pg_catalog.lower(v_project_assignment)
    ) = 0
    OR position(
      'values (new.id, new.owner_id, ''owner'', ''active'')'
      IN pg_catalog.lower(v_project_assignment)
    ) > 0 THEN
    RAISE EXCEPTION 'project Owner minting or owner_id authority remains';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM pg_catalog.pg_trigger AS trigger_row
    JOIN pg_catalog.pg_class AS table_row
      ON table_row.oid = trigger_row.tgrelid
    JOIN pg_catalog.pg_namespace AS schema_row
      ON schema_row.oid = table_row.relnamespace
    WHERE NOT trigger_row.tgisinternal
      AND (
        (
          schema_row.nspname = 'auth'
          AND table_row.relname = 'users'
          AND trigger_row.tgname IN (
            'on_auth_user_created',
            'on_auth_user_account_created'
          )
        )
        OR (
          schema_row.nspname = 'public'
          AND table_row.relname = 'projects'
          AND trigger_row.tgname = 'projects_owner_membership'
        )
      )
  ) THEN
    RAISE EXCEPTION 'an automatic Auth/project Owner-minting trigger remains';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM pg_catalog.pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'organization_memberships'
      AND policyname IN (
        'organization_memberships_manage_insert',
        'organization_memberships_manage_update',
        'organization_memberships_manage_delete'
      )
  )
    OR pg_catalog.has_table_privilege(
      'authenticated', 'public.organization_memberships', 'INSERT'
    )
    OR pg_catalog.has_table_privilege(
      'authenticated', 'public.organization_memberships', 'UPDATE'
    )
    OR pg_catalog.has_table_privilege(
      'authenticated', 'public.organization_memberships', 'DELETE'
    ) THEN
    RAISE EXCEPTION 'direct membership DML remains available to authenticated';
  END IF;

  IF position(
    'self-directed authority changes are not allowed'
    IN pg_catalog.lower(v_member_update)
  ) = 0
    OR position(
      'existing owner access requires a dedicated transfer workflow'
      IN pg_catalog.lower(v_member_update)
    ) = 0
    OR position(
      'delegated authority exceeds the caller'
      IN pg_catalog.lower(v_member_update)
    ) = 0
    OR position(
      'new.invited_by is distinct from v_caller'
      IN pg_catalog.lower(v_invite_guard)
    ) = 0
    OR position(
      'new.expires_at <= pg_catalog.clock_timestamp()'
      IN pg_catalog.lower(v_invite_guard)
    ) = 0 THEN
    RAISE EXCEPTION 'bounded member update or secure invite reissue is incomplete';
  END IF;

  -- Mid-session revocation compatibility is a database invariant: every call
  -- re-reads active membership/client state and no owner_id branch survives.
  IF position(
    'has_org_capability' IN pg_catalog.lower(v_project_read)
  ) = 0
    OR position(
      'has_org_capability' IN pg_catalog.lower(v_project_manage)
    ) = 0
    OR position(
      'status = ''active''' IN pg_catalog.lower(v_client_read)
    ) = 0 THEN
    RAISE EXCEPTION 'authorization helpers do not re-read revocable state';
  END IF;

  IF position(
    'pg_advisory_xact_lock' IN pg_catalog.lower(v_reservation)
  ) = 0
    OR position(
      'send_log.status in (''pending'', ''sent'')'
      IN pg_catalog.lower(v_reservation)
    ) = 0
    OR position(
      '30 seconds' IN pg_catalog.lower(v_reservation)
    ) = 0
    OR position(
      'from auth.users as auth_user' IN pg_catalog.lower(v_auth_lookup)
    ) = 0
    OR position(
      'auth_user.email_confirmed_at is not null'
      IN pg_catalog.lower(v_auth_lookup)
    ) = 0 THEN
    RAISE EXCEPTION 'atomic reservation or exact Auth lookup body is incomplete';
  END IF;

  IF pg_catalog.has_function_privilege(
    'authenticated',
    'public.ensure_user_account(uuid,text,text)',
    'EXECUTE'
  )
    OR pg_catalog.has_function_privilege(
      'anon',
      'public.finalize_invite_acceptance(uuid)',
      'EXECUTE'
    )
    OR pg_catalog.has_function_privilege(
      'anon',
      'public.finalize_client_access_acceptance(uuid)',
      'EXECUTE'
    )
    OR pg_catalog.has_function_privilege(
      'authenticated',
      'public.reserve_auth_magic_link_send(text,text,text,text,jsonb)',
      'EXECUTE'
    )
    OR pg_catalog.has_function_privilege(
      'authenticated',
      'public.lookup_auth_user_by_email_exact(text)',
      'EXECUTE'
    )
    OR NOT pg_catalog.has_function_privilege(
      'service_role',
      'public.reserve_auth_magic_link_send(text,text,text,text,jsonb)',
      'EXECUTE'
    )
    OR NOT pg_catalog.has_function_privilege(
      'service_role',
      'public.lookup_auth_user_by_email_exact(text)',
      'EXECUTE'
    ) THEN
    RAISE EXCEPTION 'P0 function grant containment failed';
  END IF;

  IF EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'sandbox_exec')
    AND (
      pg_catalog.has_function_privilege(
        'sandbox_exec',
        'public.ensure_user_account(uuid,text,text)',
        'EXECUTE'
      )
      OR pg_catalog.has_function_privilege(
        'sandbox_exec',
        'public.finalize_invite_acceptance(uuid)',
        'EXECUTE'
      )
      OR pg_catalog.has_function_privilege(
        'sandbox_exec',
        'public.reserve_auth_magic_link_send(text,text,text,text,jsonb)',
        'EXECUTE'
      )
      OR pg_catalog.has_function_privilege(
        'sandbox_exec',
        'public.lookup_auth_user_by_email_exact(text)',
        'EXECUTE'
      )
    ) THEN
    RAISE EXCEPTION 'sandbox_exec retains a P0 Auth capability';
  END IF;

  -- Legacy finalize_client_access(uuid) retirement proof. The sole supported
  -- client callback finalizer is public.finalize_client_access_acceptance(uuid).
  IF pg_catalog.to_regprocedure('public.finalize_client_access(uuid)') IS NOT NULL THEN
    RAISE EXCEPTION 'legacy public.finalize_client_access(uuid) survived 01000';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM pg_catalog.pg_proc AS p
    JOIN pg_catalog.pg_namespace AS n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public'
      AND p.proname = 'finalize_client_access'
  ) THEN
    RAISE EXCEPTION 'a public.finalize_client_access overload remains after 01000';
  END IF;

END;
$auth_p0_verify$;

-- Evidence rows to capture with the release record. Every result must be false
-- except service_role_can_execute, which must be true.
SELECT
  pg_catalog.has_table_privilege(
    'authenticated', 'public.organization_memberships', 'INSERT'
  ) AS authenticated_can_insert_membership,
  pg_catalog.has_table_privilege(
    'authenticated', 'public.organization_memberships', 'UPDATE'
  ) AS authenticated_can_update_membership,
  pg_catalog.has_table_privilege(
    'authenticated', 'public.organization_memberships', 'DELETE'
  ) AS authenticated_can_delete_membership,
  pg_catalog.has_function_privilege(
    'authenticated',
    'public.reserve_auth_magic_link_send(text,text,text,text,jsonb)',
    'EXECUTE'
  ) AS authenticated_can_reserve_send,
  pg_catalog.has_function_privilege(
    'service_role',
    'public.reserve_auth_magic_link_send(text,text,text,text,jsonb)',
    'EXECUTE'
  ) AS service_role_can_execute;

ROLLBACK;
