/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedEstimatesRouteImport } from './routes/_authenticated/estimates'
import { Route as AuthenticatedEstimateMastersRouteImport } from './routes/_authenticated/estimate-masters'
import { Route as AuthenticatedCostLibraryRouteImport } from './routes/_authenticated/cost-library'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiAuthMagicLinkRouteImport } from './routes/api/auth/magic-link'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects.$projectId'
import { Route as AuthenticatedEstimatesEstimateIdRouteImport } from './routes/_authenticated/estimates.$estimateId'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiStripeConnectAccountLinkRouteImport } from './routes/api/stripe/connect/account-link'
import { Route as ApiStripeCheckoutSubscriptionRouteImport } from './routes/api/stripe/checkout/subscription'
import { Route as ApiStripeCheckoutInvoiceRouteImport } from './routes/api/stripe/checkout/invoice'
import { Route as ApiStripeCheckoutCreditsRouteImport } from './routes/api/stripe/checkout/credits'
import { Route as ApiCompanyAssetsLogoRouteImport } from './routes/api/company/assets/logo'
import { Route as AuthenticatedProjectsProjectIdScheduleRouteImport } from './routes/_authenticated/projects.$projectId.schedule'
import { Route as AuthenticatedEstimatesEstimateIdPlanRoomRouteImport } from './routes/_authenticated/estimates.$estimateId.plan-room'
import { Route as AuthenticatedClientProjectsProjectIdRouteImport } from './routes/_authenticated/client.projects.$projectId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstimatesRoute = AuthenticatedEstimatesRouteImport.update({
  id: '/estimates',
  path: '/estimates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstimateMastersRoute =
  AuthenticatedEstimateMastersRouteImport.update({
    id: '/estimate-masters',
    path: '/estimate-masters',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCostLibraryRoute =
  AuthenticatedCostLibraryRouteImport.update({
    id: '/cost-library',
    path: '/cost-library',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMagicLinkRoute = ApiAuthMagicLinkRouteImport.update({
  id: '/api/auth/magic-link',
  path: '/api/auth/magic-link',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstimatesEstimateIdRoute =
  AuthenticatedEstimatesEstimateIdRouteImport.update({
    id: '/$estimateId',
    path: '/$estimateId',
    getParentRoute: () => AuthenticatedEstimatesRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeConnectAccountLinkRoute =
  ApiStripeConnectAccountLinkRouteImport.update({
    id: '/api/stripe/connect/account-link',
    path: '/api/stripe/connect/account-link',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStripeCheckoutSubscriptionRoute =
  ApiStripeCheckoutSubscriptionRouteImport.update({
    id: '/api/stripe/checkout/subscription',
    path: '/api/stripe/checkout/subscription',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStripeCheckoutInvoiceRoute =
  ApiStripeCheckoutInvoiceRouteImport.update({
    id: '/api/stripe/checkout/invoice',
    path: '/api/stripe/checkout/invoice',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStripeCheckoutCreditsRoute =
  ApiStripeCheckoutCreditsRouteImport.update({
    id: '/api/stripe/checkout/credits',
    path: '/api/stripe/checkout/credits',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCompanyAssetsLogoRoute = ApiCompanyAssetsLogoRouteImport.update({
  id: '/api/company/assets/logo',
  path: '/api/company/assets/logo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsProjectIdScheduleRoute =
  AuthenticatedProjectsProjectIdScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedEstimatesEstimateIdPlanRoomRoute =
  AuthenticatedEstimatesEstimateIdPlanRoomRouteImport.update({
    id: '/plan-room',
    path: '/plan-room',
    getParentRoute: () => AuthenticatedEstimatesEstimateIdRoute,
  } as any)
const AuthenticatedClientProjectsProjectIdRoute =
  AuthenticatedClientProjectsProjectIdRouteImport.update({
    id: '/client/projects/$projectId',
    path: '/client/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/cost-library': typeof AuthenticatedCostLibraryRoute
  '/estimate-masters': typeof AuthenticatedEstimateMastersRoute
  '/estimates': typeof AuthenticatedEstimatesRouteWithChildren
  '/team': typeof AuthenticatedTeamRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/estimates/$estimateId': typeof AuthenticatedEstimatesEstimateIdRouteWithChildren
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/api/auth/magic-link': typeof ApiAuthMagicLinkRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/client/projects/$projectId': typeof AuthenticatedClientProjectsProjectIdRoute
  '/estimates/$estimateId/plan-room': typeof AuthenticatedEstimatesEstimateIdPlanRoomRoute
  '/projects/$projectId/schedule': typeof AuthenticatedProjectsProjectIdScheduleRoute
  '/api/company/assets/logo': typeof ApiCompanyAssetsLogoRoute
  '/api/stripe/checkout/credits': typeof ApiStripeCheckoutCreditsRoute
  '/api/stripe/checkout/invoice': typeof ApiStripeCheckoutInvoiceRoute
  '/api/stripe/checkout/subscription': typeof ApiStripeCheckoutSubscriptionRoute
  '/api/stripe/connect/account-link': typeof ApiStripeConnectAccountLinkRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/cost-library': typeof AuthenticatedCostLibraryRoute
  '/estimate-masters': typeof AuthenticatedEstimateMastersRoute
  '/estimates': typeof AuthenticatedEstimatesRouteWithChildren
  '/team': typeof AuthenticatedTeamRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/': typeof AuthenticatedIndexRoute
  '/estimates/$estimateId': typeof AuthenticatedEstimatesEstimateIdRouteWithChildren
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/api/auth/magic-link': typeof ApiAuthMagicLinkRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/client/projects/$projectId': typeof AuthenticatedClientProjectsProjectIdRoute
  '/estimates/$estimateId/plan-room': typeof AuthenticatedEstimatesEstimateIdPlanRoomRoute
  '/projects/$projectId/schedule': typeof AuthenticatedProjectsProjectIdScheduleRoute
  '/api/company/assets/logo': typeof ApiCompanyAssetsLogoRoute
  '/api/stripe/checkout/credits': typeof ApiStripeCheckoutCreditsRoute
  '/api/stripe/checkout/invoice': typeof ApiStripeCheckoutInvoiceRoute
  '/api/stripe/checkout/subscription': typeof ApiStripeCheckoutSubscriptionRoute
  '/api/stripe/connect/account-link': typeof ApiStripeConnectAccountLinkRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/cost-library': typeof AuthenticatedCostLibraryRoute
  '/_authenticated/estimate-masters': typeof AuthenticatedEstimateMastersRoute
  '/_authenticated/estimates': typeof AuthenticatedEstimatesRouteWithChildren
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/estimates/$estimateId': typeof AuthenticatedEstimatesEstimateIdRouteWithChildren
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/api/auth/magic-link': typeof ApiAuthMagicLinkRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/client/projects/$projectId': typeof AuthenticatedClientProjectsProjectIdRoute
  '/_authenticated/estimates/$estimateId/plan-room': typeof AuthenticatedEstimatesEstimateIdPlanRoomRoute
  '/_authenticated/projects/$projectId/schedule': typeof AuthenticatedProjectsProjectIdScheduleRoute
  '/api/company/assets/logo': typeof ApiCompanyAssetsLogoRoute
  '/api/stripe/checkout/credits': typeof ApiStripeCheckoutCreditsRoute
  '/api/stripe/checkout/invoice': typeof ApiStripeCheckoutInvoiceRoute
  '/api/stripe/checkout/subscription': typeof ApiStripeCheckoutSubscriptionRoute
  '/api/stripe/connect/account-link': typeof ApiStripeConnectAccountLinkRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/billing'
    | '/cost-library'
    | '/estimate-masters'
    | '/estimates'
    | '/team'
    | '/auth/callback'
    | '/email/unsubscribe'
    | '/estimates/$estimateId'
    | '/projects/$projectId'
    | '/api/auth/magic-link'
    | '/api/stripe/webhook'
    | '/lovable/email/suppression'
    | '/client/projects/$projectId'
    | '/estimates/$estimateId/plan-room'
    | '/projects/$projectId/schedule'
    | '/api/company/assets/logo'
    | '/api/stripe/checkout/credits'
    | '/api/stripe/checkout/invoice'
    | '/api/stripe/checkout/subscription'
    | '/api/stripe/connect/account-link'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/admin'
    | '/billing'
    | '/cost-library'
    | '/estimate-masters'
    | '/estimates'
    | '/team'
    | '/auth/callback'
    | '/email/unsubscribe'
    | '/'
    | '/estimates/$estimateId'
    | '/projects/$projectId'
    | '/api/auth/magic-link'
    | '/api/stripe/webhook'
    | '/lovable/email/suppression'
    | '/client/projects/$projectId'
    | '/estimates/$estimateId/plan-room'
    | '/projects/$projectId/schedule'
    | '/api/company/assets/logo'
    | '/api/stripe/checkout/credits'
    | '/api/stripe/checkout/invoice'
    | '/api/stripe/checkout/subscription'
    | '/api/stripe/connect/account-link'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/billing'
    | '/_authenticated/cost-library'
    | '/_authenticated/estimate-masters'
    | '/_authenticated/estimates'
    | '/_authenticated/team'
    | '/auth/callback'
    | '/email/unsubscribe'
    | '/_authenticated/'
    | '/_authenticated/estimates/$estimateId'
    | '/_authenticated/projects/$projectId'
    | '/api/auth/magic-link'
    | '/api/stripe/webhook'
    | '/lovable/email/suppression'
    | '/_authenticated/client/projects/$projectId'
    | '/_authenticated/estimates/$estimateId/plan-room'
    | '/_authenticated/projects/$projectId/schedule'
    | '/api/company/assets/logo'
    | '/api/stripe/checkout/credits'
    | '/api/stripe/checkout/invoice'
    | '/api/stripe/checkout/subscription'
    | '/api/stripe/connect/account-link'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ApiAuthMagicLinkRoute: typeof ApiAuthMagicLinkRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiCompanyAssetsLogoRoute: typeof ApiCompanyAssetsLogoRoute
  ApiStripeCheckoutCreditsRoute: typeof ApiStripeCheckoutCreditsRoute
  ApiStripeCheckoutInvoiceRoute: typeof ApiStripeCheckoutInvoiceRoute
  ApiStripeCheckoutSubscriptionRoute: typeof ApiStripeCheckoutSubscriptionRoute
  ApiStripeConnectAccountLinkRoute: typeof ApiStripeConnectAccountLinkRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estimates': {
      id: '/_authenticated/estimates'
      path: '/estimates'
      fullPath: '/estimates'
      preLoaderRoute: typeof AuthenticatedEstimatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estimate-masters': {
      id: '/_authenticated/estimate-masters'
      path: '/estimate-masters'
      fullPath: '/estimate-masters'
      preLoaderRoute: typeof AuthenticatedEstimateMastersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cost-library': {
      id: '/_authenticated/cost-library'
      path: '/cost-library'
      fullPath: '/cost-library'
      preLoaderRoute: typeof AuthenticatedCostLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/magic-link': {
      id: '/api/auth/magic-link'
      path: '/api/auth/magic-link'
      fullPath: '/api/auth/magic-link'
      preLoaderRoute: typeof ApiAuthMagicLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estimates/$estimateId': {
      id: '/_authenticated/estimates/$estimateId'
      path: '/$estimateId'
      fullPath: '/estimates/$estimateId'
      preLoaderRoute: typeof AuthenticatedEstimatesEstimateIdRouteImport
      parentRoute: typeof AuthenticatedEstimatesRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/connect/account-link': {
      id: '/api/stripe/connect/account-link'
      path: '/api/stripe/connect/account-link'
      fullPath: '/api/stripe/connect/account-link'
      preLoaderRoute: typeof ApiStripeConnectAccountLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/checkout/subscription': {
      id: '/api/stripe/checkout/subscription'
      path: '/api/stripe/checkout/subscription'
      fullPath: '/api/stripe/checkout/subscription'
      preLoaderRoute: typeof ApiStripeCheckoutSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/checkout/invoice': {
      id: '/api/stripe/checkout/invoice'
      path: '/api/stripe/checkout/invoice'
      fullPath: '/api/stripe/checkout/invoice'
      preLoaderRoute: typeof ApiStripeCheckoutInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/checkout/credits': {
      id: '/api/stripe/checkout/credits'
      path: '/api/stripe/checkout/credits'
      fullPath: '/api/stripe/checkout/credits'
      preLoaderRoute: typeof ApiStripeCheckoutCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/company/assets/logo': {
      id: '/api/company/assets/logo'
      path: '/api/company/assets/logo'
      fullPath: '/api/company/assets/logo'
      preLoaderRoute: typeof ApiCompanyAssetsLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/$projectId/schedule': {
      id: '/_authenticated/projects/$projectId/schedule'
      path: '/schedule'
      fullPath: '/projects/$projectId/schedule'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdScheduleRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/estimates/$estimateId/plan-room': {
      id: '/_authenticated/estimates/$estimateId/plan-room'
      path: '/plan-room'
      fullPath: '/estimates/$estimateId/plan-room'
      preLoaderRoute: typeof AuthenticatedEstimatesEstimateIdPlanRoomRouteImport
      parentRoute: typeof AuthenticatedEstimatesEstimateIdRoute
    }
    '/_authenticated/client/projects/$projectId': {
      id: '/_authenticated/client/projects/$projectId'
      path: '/client/projects/$projectId'
      fullPath: '/client/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedClientProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedEstimatesEstimateIdRouteChildren {
  AuthenticatedEstimatesEstimateIdPlanRoomRoute: typeof AuthenticatedEstimatesEstimateIdPlanRoomRoute
}

const AuthenticatedEstimatesEstimateIdRouteChildren: AuthenticatedEstimatesEstimateIdRouteChildren =
  {
    AuthenticatedEstimatesEstimateIdPlanRoomRoute:
      AuthenticatedEstimatesEstimateIdPlanRoomRoute,
  }

const AuthenticatedEstimatesEstimateIdRouteWithChildren =
  AuthenticatedEstimatesEstimateIdRoute._addFileChildren(
    AuthenticatedEstimatesEstimateIdRouteChildren,
  )

interface AuthenticatedEstimatesRouteChildren {
  AuthenticatedEstimatesEstimateIdRoute: typeof AuthenticatedEstimatesEstimateIdRouteWithChildren
}

const AuthenticatedEstimatesRouteChildren: AuthenticatedEstimatesRouteChildren =
  {
    AuthenticatedEstimatesEstimateIdRoute:
      AuthenticatedEstimatesEstimateIdRouteWithChildren,
  }

const AuthenticatedEstimatesRouteWithChildren =
  AuthenticatedEstimatesRoute._addFileChildren(
    AuthenticatedEstimatesRouteChildren,
  )

interface AuthenticatedProjectsProjectIdRouteChildren {
  AuthenticatedProjectsProjectIdScheduleRoute: typeof AuthenticatedProjectsProjectIdScheduleRoute
}

const AuthenticatedProjectsProjectIdRouteChildren: AuthenticatedProjectsProjectIdRouteChildren =
  {
    AuthenticatedProjectsProjectIdScheduleRoute:
      AuthenticatedProjectsProjectIdScheduleRoute,
  }

const AuthenticatedProjectsProjectIdRouteWithChildren =
  AuthenticatedProjectsProjectIdRoute._addFileChildren(
    AuthenticatedProjectsProjectIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedCostLibraryRoute: typeof AuthenticatedCostLibraryRoute
  AuthenticatedEstimateMastersRoute: typeof AuthenticatedEstimateMastersRoute
  AuthenticatedEstimatesRoute: typeof AuthenticatedEstimatesRouteWithChildren
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRouteWithChildren
  AuthenticatedClientProjectsProjectIdRoute: typeof AuthenticatedClientProjectsProjectIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedCostLibraryRoute: AuthenticatedCostLibraryRoute,
  AuthenticatedEstimateMastersRoute: AuthenticatedEstimateMastersRoute,
  AuthenticatedEstimatesRoute: AuthenticatedEstimatesRouteWithChildren,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedProjectsProjectIdRoute:
    AuthenticatedProjectsProjectIdRouteWithChildren,
  AuthenticatedClientProjectsProjectIdRoute:
    AuthenticatedClientProjectsProjectIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ApiAuthMagicLinkRoute: ApiAuthMagicLinkRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiCompanyAssetsLogoRoute: ApiCompanyAssetsLogoRoute,
  ApiStripeCheckoutCreditsRoute: ApiStripeCheckoutCreditsRoute,
  ApiStripeCheckoutInvoiceRoute: ApiStripeCheckoutInvoiceRoute,
  ApiStripeCheckoutSubscriptionRoute: ApiStripeCheckoutSubscriptionRoute,
  ApiStripeConnectAccountLinkRoute: ApiStripeConnectAccountLinkRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
