// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

type SupabaseAuthStorage = {
  getItem: (key: string) => string | null | Promise<string | null>;
  setItem: (key: string, value: string) => void | Promise<void>;
  removeItem: (key: string) => void | Promise<void>;
};

function createMemoryStorage(): SupabaseAuthStorage {
  const store = new Map<string, string>();

  return {
    getItem: (key) => store.get(key) ?? null,
    setItem: (key, value) => {
      store.set(key, value);
    },
    removeItem: (key) => {
      store.delete(key);
    },
  };
}

const memoryAuthStorage = createMemoryStorage();

function canUseWebStorage(storage: Storage, label: string) {
  try {
    const testKey = "__overwatch_supabase_storage_test__";
    storage.setItem(testKey, "1");
    storage.removeItem(testKey);
    return true;
  } catch (err) {
    console.warn(`[Supabase] ${label} is unavailable; trying the next auth storage option.`, err);
    return false;
  }
}

function getAuthStorage(): SupabaseAuthStorage | undefined {
  if (typeof window === "undefined") return undefined;

  const candidates: Array<[string, () => Storage]> = [
    ["localStorage", () => window.localStorage],
    ["sessionStorage", () => window.sessionStorage],
  ];

  for (const [label, getStorage] of candidates) {
    try {
      const storage = getStorage();
      if (canUseWebStorage(storage, label)) return storage;
    } catch (err) {
      console.warn(
        `[Supabase] ${label} cannot be accessed; trying the next auth storage option.`,
        err,
      );
    }
  }

  console.warn(
    "[Supabase] Browser storage is unavailable; using in-memory auth storage for this tab.",
  );
  return memoryAuthStorage;
}

function readRuntimeEnv(name: string) {
  const viteValue = import.meta.env[name];
  if (viteValue) return viteValue;

  const maybeProcess =
    typeof globalThis === "object" && "process" in globalThis
      ? (
          globalThis as typeof globalThis & {
            process?: { env?: Record<string, string | undefined> };
          }
        ).process
      : undefined;

  return maybeProcess?.env?.[name];
}

function createSupabaseClient() {
  const SUPABASE_URL = readRuntimeEnv("VITE_SUPABASE_URL") || readRuntimeEnv("SUPABASE_URL");
  const SUPABASE_PUBLISHABLE_KEY =
    readRuntimeEnv("VITE_SUPABASE_PUBLISHABLE_KEY") || readRuntimeEnv("SUPABASE_PUBLISHABLE_KEY");

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Check the deployment's Supabase configuration.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: getAuthStorage(),
      persistSession: true,
      autoRefreshToken: true,
      // /auth/callback owns every supported callback shape explicitly. Letting
      // auth-js inspect the same URL races the manual PKCE/token-hash exchange
      // and can consume a one-time code twice.
      detectSessionInUrl: false,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
